SitioWebColegio/Models/viewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SitioWebColegio.Models.viewModels
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name ="Usuario")]
        public string NameUser { get; set; }
        [Required]
        public string Clave { get; set; }
        [Required]
        public string Rol { get; set; } 
    }
}

SitioWebColegio/Controllers/AccesoController.cs
using SitioWebColegio.Models.viewModels;
using SitioWebColegio.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SitioWebColegio.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Login()
        {
            ViewBag.noExiste = ViewData["NoExiste"];
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        { 
        
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                using (DBColegioEntities db = new DBColegioEntities())
                {
                    if (model.Rol == "Administrador")
                    {
                        var oUser = (from d in db.Administrador
                                     where d.nombreusuario == model.NameUser.Trim() && d.clave == model.Clave.Trim()
                                     select d).FirstOrDefault();

                        if (oUser == null)
                        {
                            ViewData["NoExiste"] = "Usuario o Clave incorrecta";
                            return View();
                        }

                        Session["Administrador"] = oUser; 
                        Session["userTitulo"] = oUser.nombre;
                        return RedirectToAction("Index", "Administrador");

                    }

                    if (model.Rol == "Profesor")
                    {
                        var oUser = (from d in db.Profesor
                                     where d.nombreUsuario == model.NameUser.Trim() && d.clave== model.Clave.Trim()
                                     select d).FirstOrDefault();
                         
                        if (oUser == null)
                        {
                            ViewData["NoExiste"] = "Usuario o Clave incorrecta";
                            return View();
                        }

                        Session["Profesor"] = oUser;
                        Session["userTitulo"] = oUser.nombre;
                        return RedirectToAction("AlumnosProfesor", "Profesor");

                    }

                    if (model.Rol == "Alumno")
                    {
                        var oUser = (from d in db.Alumno
                                     where d.nombreUsuario == model.NameUser.Trim() && d.clave == model.Clave.Trim()
                                     select d).FirstOrDefault();

                        if (oUser == null)
                        {
                            ViewData["NoExiste"] = "Usuario o Clave incorrecta";
                            return View();
                        }

                        Session["Alumno"] = oUser;
                        Session["userTitulo"] = oUser.nombre;

                        return RedirectToAction("MateriasAlumnos", "Alumno");
                    }
                }
          
            }

            catch (Exception ex)
            {
                return View();
            }

           return View();


        }

        public ActionResult Logof()
        {
            Session["Administrador"] = null;
            Session["Profesor"] = null;
            Session["Alumno"] = null;
            Session["userTitulo"] = null;

            return RedirectToAction("Index", "Home");
        }
    }
}

SitioWebColegio/Views/Acceso/Login.cshtml
@model SitioWebColegio.Models.viewModels.LoginViewModel
@{
    ViewBag.Title = "Iniciar Sesion";
    Layout = "~/Views/Shared/LayoutLogin.cshtml";
}

<div class="form-signin mt-4">
    <form method="post" action="@Url.Action("Login","Acceso")">
        <h1 class="h3 mb-3 fw-normal text-white text-center">Inicicar Sesion</h1>
        @if (ViewBag.noExiste != null)
        {
            <h5 class="text-danger text-center">@ViewBag.noExiste</h5>

        }
        <div class="form-floating">
            <input name="NameUser" class="form-control" id="floatingInput" placeholder="Ingrese Su Usuario">
            <label for="floatingInput">Usuario</label>
            @Html.ValidationMessageFor(d => d.NameUser, "", new { @class = "text-danger" })
        </div>
        <div class="form-floating">
            <input name="Clave" autocomplete="off" type="password" class="form-control" id="floatingPassword" placeholder="Ingrese su clave">
            <label for="floatingPassword">Clave</label>
            @Html.ValidationMessageFor(d => d.Clave, "", new { @class = "text-danger" })

        </div>
        <div class="form-floating">
            <select name="Rol">
                <option value="">Seleccione</option>
                <option value="Profesor" name="Rol">Profesor</option>
                <option value="Alumno" name="Rol">Alumno</option>
                <option value="Administrador" name="Rol">Administrador</option>
            </select><br />
            @Html.ValidationMessageFor(d => d.Rol, "", new { @class = "text-danger" })

        </div>
        <button class="w-100 btn btn-lg" style="background-color: #9f8ad0; color: white;" type="submit">Entrar</button>
    </form>
</div>